name: 'Linter less or equal action'
description: 'Ensure that there are less or equal Linter warnings'
inputs:
  name:  # id of input
    description: 'What to lint'
    required: true
  command:
    description: Tool to use
    required: true
  total_regexp:
    description: the extractor
    required: true
  warnings_regexp:
    description: the extractor
    required: true
  errors_regexp:
    description: the extractor
    required: true
  cwd:
    description: place to execute command
    required: true
  compare_branch:
    description: which branch to compare with
    required: true
  mode:
    description: Mode of the compare (all vs. changed)
    required: true
outputs:
  pass:
    description: Whether the check has passed
  errors: # id of output
    description: 'The results of the linting process'
  warnings:
    description: "Number of warnings"
runs:
  using: 'node12'
  main: 'dist/index.js'
