name: 'Linter less or equal action'
description: 'Ensure that there are less or equal Linter problems'
inputs:
  name:  # id of input
    description: 'What to lint'
    required: true
  command:
    description: Tool to use
    required: true
  total_regexp:
    description: the extractor
    required: true
  problems_regexp:
    description: the extractor
    required: true
  errors_regexp:
    description: the extractor
    required: true
outputs:
  pass:
    description: Whether the check has passed
  results: # id of output
    description: 'The results of the linting process'
runs:
  using: 'node12'
  main: 'dist/index.js'
