on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to check linter errors
    steps:
    - uses: actions/checkout@v2
    - name: Linter count
      id: hello
      uses: henrixapp/linter-less-or-equal-action@v1.12
      with:
        name: EsLint
        command: npx eslint  
        total_regexp: \d+ problems
        errors_regexp: \d+ errors
        warnings_regexp: \d+ warnings
        compare_branch: main
        mode: changed
        include: ".js"
